stage:
  deploy:
    ENABLE_GOOGLE_ANALYTICS: true
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    CONSUMERS_WAIT_FOR_MAX_MESSAGES: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: []
      multiple_processes:
        async.operations.all: 4
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'   
integration:
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: []
      multiple_processes:
        async.operations.all: 4
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'