<div class="entry-edit form-inline">
    <fieldset class="fieldset admin__fieldset " id="base_fieldset">
        <legend class="admin__legend legend">
        <span><?= /* @noEscape */ __('Customer Order Frequency') ?></span>
        </legend><br>
        <div class="messages">
        </div>
        <div class="admin__field field field-entity  with-addon" data-ui-id="import-form-container-form-fieldset-element-form-field-entity">
            <label class="label admin__field-label" for="entity">
                <a target="_blank" href="<?= /* @noEscape */ $block->getCsvPath() ?>"><span><?= /* @noEscape */ __('Sample file downlaod') ?></span></a>
            </label>
            
        </div>
    </fieldset>
</div>