<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="dashboard-container row">
    <div class="dashboard-main">
        <div class="dashboard-order-stats" style="margin-top: 30px;">
            <?= $block->getChildHtml('batOrderStats') ?>
        </div>
        <div class="dashboard-vba-stats" style="margin-top: 30px;">
            <?= $block->getChildHtml('batVbaStats') ?>
        </div>
    </div>
</div>
